name: {{app_name}}
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1
environment:
  flutter: '>=3.13.0 <4.0.0'
  sdk: '>=3.0.0 <4.0.0'






dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^4.13.2
  firebase_core: ^2.23.0
  firebase_crashlytics: ^3.4.5

  # Backend
  get_it: ^7.6.4

  # UI
  animated_list_plus: ^0.5.2
  cupertino_icons: ^1.0.6
  flutter_form_builder: ^9.1.1
  enough_platform_widgets: ^1.0.0

  # Utils
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  form_builder_validators: ^9.1.0
  go_router: ^12.1.1
  intl: ^0.18.1
  intl_utils: ^2.8.5

  # Data
  envied: ^0.5.2
  fpdart: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # Networking
  dio: ^5.3.4

  # Logging
  talker: ^3.1.4
  talker_dio_logger: ^2.3.1

  # State management
  equatable: ^2.0.5
  informers: ^0.0.3+1
  provider: ^6.1.1






dev_dependencies:
  # Generators
  build_runner: ^2.4.6
  envied_generator: ^0.5.2

  # Analysis
  analyzer: ^5.13.0
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

  # Testing
  flutter_test:
    sdk: flutter
  faker: ^2.1.0
  gherkin_unit_test: ^0.0.5
  mockito: ^5.4.3


  # Bundling
  #dart run dependency_validator
  dependency_validator: ^3.2.3
  #dart run dart_code_metrics:metrics check-unused-files lib
#  dart_code_metrics: ^5.6.0
  flutter_flavorizr: ^2.2.1
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1






flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logos/






flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: "en"
  output_dir: lib/l10n/generated
  line_length: 100
  # use_deferred_loading: true
