#ignore_for_file: sort_pub_dependencies

name: {{app_name}}
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1
environment:
  flutter: '>=3.29.0 <4.0.0'
  sdk: '>=3.7.0 <4.0.0'






dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^5.6.6
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  firebase_remote_config: ^5.4.2

  # Backend
  get_it: ^8.0.3

  # UI
  animated_reorderable_list: ^1.2.0
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  enough_platform_widgets:
    git:
      url: https://github.com/LahaLuhem/enough_platform_widgets.git
      ref: "main"
  flutter_animate: ^4.5.2
  flutter_form_builder: ^10.0.1
  flutter_spinbox:
    git:
      url: https://github.com/Didata-Automatisering/flutter_spinbox.git
      ref: "feature/🔴-cupertino-validator-error"
  flutter_typeahead:
    git:
      url: https://github.com/Didata-Automatisering/flutter_typeahead.git
      ref: "feature/prevent-on-text-changed-from-triggering-when-not-focused"
  font_awesome_flutter:
    git:
      url: git@didata.gitlab.host:didata-automatisering/app-tech/apps/libraries/font_awesome_flutter.git
      ref: "master"
  gap: ^3.0.1
  tap_debouncer: ^2.2.0

  # Utils
  conditional_parent_widget: ^0.0.2
  flutter_helper_utils: ^8.0.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^11.1.2
  fuzzywuzzy: ^1.2.0
  go_router: ^14.8.1
  intl: ^0.20.2
  maps_launcher: 3.0.0+1
  package_info_plus: ^8.3.0
  printing: ^5.14.2
  pull_to_refresh: ^2.0.0
  scanwedge: ^1.0.4
  flutter_barcode_scanner:
    git:
      url: https://github.com/iceman3383/flutter_barcode_scanner.git
      ref: "3eeddcb47ea16f662c1499169ec6d1d150199e90"
  url_launcher: ^6.3.1

  # Data
  built_collection: ^5.1.1
  collection: ^1.19.1
  envied: ^1.1.1
  fpdart: ^1.1.1
  flutter_secure_storage: ^9.2.4
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4

  # Networking
  dio: ^5.8.0+1

  # Logging
  talker: ^4.7.1
  talker_dio_logger: ^4.7.1

  # State management
  equatable: ^2.0.7
  informers: ^0.0.3+2
  multi_value_listenable_builder_typed: ^0.1.1
  rxdart: ^0.28.0
  veto: ^0.0.15






dev_dependencies:
  # Generators
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  hive_ce_generator: ^1.8.2
  intl_utils: ^2.8.10

  # Analysis
  very_good_analysis: ^7.0.0
  dart_code_metrics_presets: ^2.21.0

  # Testing
  flutter_test:
    sdk: flutter
  faker: ^2.2.0
  gherkin_unit_test: ^0.0.5
  mockito: ^5.4.5
  test_cov_console: ^0.2.2


  # Bundling
  #dart run cider log added "<name>"
  cider: ^0.2.8
  #dart run dependency_validator
  dependency_validator: ^5.0.2
  #dart run dart_code_metrics:metrics check-unused-files lib --disable-sunset-warning
#  dart_code_metrics: ^5.6.0
  flutter_flavorizr: ^2.3.0
  #dart run flutter_launcher_icons -f flutter_launcher_icons*
  flutter_launcher_icons: ^0.14.3
  #dart run flutter_native_splash:create --all-flavors
  flutter_native_splash: ^2.4.5






flutter:
  generate: true
  uses-material-design: true
#  disable-swift-package-manager: true

  assets:
    - assets/icons/
    - assets/logos/






flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: "en"
  output_dir: lib/l10n/generated
  line_length: 100
  # use_deferred_loading: true
