name: {{app_name}}
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1
environment:
  flutter: '>=3.22.0 <4.0.0'
  sdk: '>=3.0.0 <4.0.0'






dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^4.17.5
  firebase_analytics: ^10.10.7
  firebase_core: ^2.32.0
  firebase_crashlytics: ^3.5.7
  firebase_remote_config: ^4.4.7

  # Backend
  get_it: ^7.7.0

  # UI
  auto_size_text: ^3.0.0
  animated_list_plus: ^0.5.2
  cupertino_icons: ^1.0.8
  enough_platform_widgets: ^1.0.0
  flutter_form_builder: ^9.3.0
  gap: ^3.0.1

  # Utils
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^10.0.1
  go_router: ^14.1.4
  intl: ^0.19.0
  intl_utils: ^2.8.7

  # Data
  envied: ^0.5.4+1
  fpdart: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

  # Networking
  dio: ^5.4.3+1

  # Logging
  talker: ^3.1.4
  talker_dio_logger: ^2.3.1

  # State management
  equatable: ^2.0.5
  informers: ^0.0.3+1
  provider: ^6.1.2
  veto: ^0.0.10






dev_dependencies:
  # Generators
  build_runner: ^2.4.10
  envied_generator: ^0.5.4+1
  hive_generator: ^2.0.1

  # Analysis
  analyzer: ^6.0.0
  flutter_lints: ^4.0.0
  very_good_analysis: ^5.1.0

  # Testing
  flutter_test:
    sdk: flutter
  faker: ^2.1.0
  gherkin_unit_test: ^0.0.5
  mockito: ^5.4.4


  # Bundling
  #dart run dependency_validator
  dependency_validator: ^3.2.3
  #dart run dart_code_metrics:metrics check-unused-files lib --disable-sunset-warning
#  dart_code_metrics: ^5.6.0
  flutter_flavorizr: ^2.2.3
  #dart run flutter_launcher_icons:main -f flutter_launcher_icons*
  flutter_launcher_icons: ^0.13.1
  #dart run flutter_native_splash:create --flavors develop,prod
  flutter_native_splash: ^2.4.0






flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logos/






flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: "en"
  output_dir: lib/l10n/generated
  line_length: 100
  # use_deferred_loading: true
